const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const artifacts=path.resolve('test-artifacts');fs.mkdirSync(artifacts,{recursive:true});
const userDir=fs.mkdtempSync(path.join(os.tmpdir(),'kaarnegar-test-'));
const pdf=path.join(artifacts,'گزارش-آزمایشی.pdf');
let app;
const errors=[];
async function launch(){const env={...process.env,KAARNEGAR_DATA_DIR:userDir,KAARNEGAR_TEST_PDF:pdf};delete env.ELECTRON_RUN_AS_NODE;const executablePath=process.env.KAARNEGAR_TEST_EXECUTABLE;app=await electron.launch({executablePath,args:executablePath?[]:[path.resolve('.')],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'زمان خود را ارزشمند کنید.'}).waitFor();return page}
(async()=>{try{
 let page=await launch();
 assert.equal(await page.evaluate(()=>document.documentElement.dir),'rtl');
 await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.evaluate(()=>document.fonts.check('14px Arad')),true);
 await page.getByRole('button',{name:'تنظیمات',exact:true}).click();
 await page.getByPlaceholder('نام و نام خانوادگی').fill('مریم احمدی');
 await page.getByRole('textbox',{name:'دستمزد ساعتی',exact:true}).fill('۲۵۰۰۰۰');
 await page.getByRole('button',{name:'ذخیرهٔ تنظیمات'}).click();
 await page.getByRole('status').filter({hasText:'تنظیمات ذخیره شد.'}).waitFor();
 await page.getByRole('button',{name:'ثبت زمان',exact:true}).click();
 await page.getByRole('button',{name:'ثبت دستی زمان',exact:true}).first().click();
 await page.getByRole('textbox',{name:'عنوان ثبت دستی'}).fill('طراحی رابط کاربری');
 await page.getByRole('textbox',{name:'ساعت',exact:true}).fill('۱');
 await page.getByRole('textbox',{name:'دقیقه',exact:true}).fill('۳۰');
 await page.getByRole('button',{name:'ذخیرهٔ زمان',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 let stored=JSON.parse(fs.readFileSync(path.join(userDir,'work-data.json'),'utf8'));
 assert.equal(stored.entries[0].durationMs,5400000);assert.equal(stored.entries[0].rate,250000);
 await page.getByRole('textbox',{name:'عنوان فعالیت',exact:true}).fill('برنامه‌نویسی کارنگار');
 await page.getByRole('button',{name:/شروع فعالیت/}).click();
 await page.waitForTimeout(1300);
 await page.getByRole('button',{name:'مکث',exact:true}).click();
 const paused=await page.locator('.timer-digits').innerText();
 await page.waitForTimeout(1100);assert.equal(await page.locator('.timer-digits').innerText(),paused);
 await page.getByRole('button',{name:'ادامهٔ فعالیت'}).click();
 await page.waitForTimeout(1100);
 await page.getByRole('button',{name:'توقف و ذخیره'}).click();
 await page.getByRole('button',{name:'ویجت کوچک'}).click();
 await page.locator('.compact').waitFor();
 const widget=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return {top:w.isAlwaysOnTop(),size:w.getSize()}});
 assert.equal(widget.top,true);assert.ok(Math.abs(widget.size[0]-430)<=2);
 await page.screenshot({path:path.join(artifacts,'widget.png')});
 await page.getByRole('button',{name:'نمای کامل'}).click();
 await page.locator('.sidebar').waitFor();
 await page.screenshot({path:path.join(artifacts,'dashboard.png')});
 await page.getByRole('button',{name:'گزارش‌ها',exact:true}).click();
 await page.getByRole('button',{name:'امروز',exact:true}).click();
 await page.getByRole('button',{name:'از تاریخ',exact:true}).click();
 await page.locator('.calendar').waitFor();
 await page.getByRole('button',{name:'امروز',exact:true}).last().click();
 await page.getByRole('textbox',{name:'جست‌وجوی فعالیت'}).fill('طراحی');
 await page.getByRole('button',{name:'دریافت گزارش PDF'}).click();
 await page.getByRole('status').filter({hasText:'گزارش PDF ذخیره شد.'}).waitFor();
 assert.equal(fs.readFileSync(pdf).subarray(0,4).toString(),'%PDF');assert.ok(fs.statSync(pdf).size>10000);
 const pdfBytes=fs.readFileSync(pdf).toString('latin1');
 assert.ok(/\/BaseFont\s*\/\w*\+?Arad/.test(pdfBytes),'PDF must embed Arad, rather than a system fallback');
 assert.ok(/\/FontFile[23]/.test(pdfBytes),'PDF must contain the font data');
 await page.getByRole('textbox',{name:'جست‌وجوی فعالیت'}).fill('');
 await page.screenshot({path:path.join(artifacts,'reports.png'),fullPage:true});
 await page.getByRole('button',{name:'ویرایش طراحی رابط کاربری'}).click();
 await page.getByRole('textbox',{name:'دقیقه',exact:true}).fill('۴۵');
 await page.getByRole('button',{name:'ذخیرهٔ زمان',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 stored=JSON.parse(fs.readFileSync(path.join(userDir,'work-data.json'),'utf8'));assert.equal(stored.entries.find(e=>e.title==='طراحی رابط کاربری').durationMs,6300000);
 await page.getByRole('button',{name:'تنظیمات',exact:true}).click();
 await page.getByRole('textbox',{name:'دستمزد ساعتی',exact:true}).fill('۳۰۰۰۰۰');
 await page.getByRole('button',{name:'ذخیرهٔ تنظیمات'}).click();
 await page.getByRole('status').filter({hasText:'تنظیمات ذخیره شد.'}).waitFor();
 await page.getByRole('button',{name:'ثبت زمان',exact:true}).click();
 await page.getByRole('textbox',{name:'عنوان فعالیت',exact:true}).fill('کار ادامه‌دار');
 await page.getByRole('button',{name:/شروع فعالیت/}).click();
 await page.waitForTimeout(1100);
 // Closing the native window must persist a paused timer.
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());
 await app.close().catch(()=>{});
 stored=JSON.parse(fs.readFileSync(path.join(userDir,'work-data.json'),'utf8'));
 assert.equal(stored.active.runningSince,null);assert.ok(stored.active.segments.length>0);
 page=await launch();
 await page.getByRole('button',{name:'ادامهٔ فعالیت'}).waitFor();
 assert.equal(await page.getByRole('textbox',{name:'عنوان فعالیت',exact:true}).inputValue(),'کار ادامه‌دار');
 stored=JSON.parse(fs.readFileSync(path.join(userDir,'work-data.json'),'utf8'));
 assert.equal(stored.rate,300000);assert.equal(stored.entries.find(e=>e.title==='طراحی رابط کاربری').rate,250000);
 await page.getByRole('button',{name:'توقف و ذخیره'}).click();
 await page.getByRole('button',{name:'حذف برنامه‌نویسی کارنگار'}).click();
 await page.getByRole('button',{name:'حذف ثبت',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 stored=JSON.parse(fs.readFileSync(path.join(userDir,'work-data.json'),'utf8'));
 assert.ok(!stored.entries.some(e=>e.title==='برنامه‌نویسی کارنگار'));
 assert.deepEqual(errors,[]);
 console.log('PASS: Persian font/RTL, salary, manual entry/edit/delete, timer pause/resume, widget, Jalali calendar, PDF, persistence and close/reopen.');
 console.log('Artifacts:',artifacts);
}finally{if(app)await app.close().catch(()=>{})}})().catch(e=>{console.error(e);process.exitCode=1});
