import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowUpLeft, BarChart3, CalendarDays, Check, CheckCircle2, ChevronLeft, Clock3, Coffee, Download, FileText, LayoutDashboard, Maximize2, Minimize2, Pause, Pencil, Play, Plus, Search, Settings2, ShieldCheck, Square, Timer, Trash2, Upload, Wallet, X } from 'lucide-react';
import DatePicker from './DatePicker';
import WindowBar from './WindowBar';
import { activeDuration, checkpoint, dateLabel, digits, duration, emptyState, filtered, fromDate, finishActive, groupTasks, latin, localDate, number, pauseActive, rangePreset, totals, type Entry, type State } from './model';
import { reportHTML } from './report';
type Page = 'timer'|'reports'|'settings';
type Form = { id?:string; title:string; date:string; hours:string; minutes:string; seconds:string; rate:string };
const colors=['#168b78','#7c6cc8','#d69c48','#598dc7','#c87883'];
function Modal({ title, children, close }: {title:string;children:ReactNode;close:()=>void}) {
  const box=useRef<HTMLDivElement>(null), closeRef=useRef(close);closeRef.current=close;
  useEffect(()=>{ const old=document.activeElement as HTMLElement; box.current?.querySelector<HTMLInputElement>('input')?.focus(); if(!box.current?.contains(document.activeElement))box.current?.focus(); const key=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const els=box.current?.querySelectorAll<HTMLElement>('button,input,select,[tabindex="0"]'); if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);old?.focus()}},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="بستن" onClick={close}><X size={20}/></button></div>{children}</div></div>;
}
export default function App() {
  const [state,setState]=useState<State>(emptyState), current=useRef(state), [loaded,setLoaded]=useState(false), [busy,setBusy]=useState(false), lock=useRef(false);
  const [page,setPage]=useState<Page>('timer'), [now,setNow]=useState(Date.now()), [title,setTitle]=useState(''), [compact,setCompact]=useState(false), [toast,setToast]=useState(''), [error,setError]=useState(''), [warning,setWarning]=useState(''), [dataPath,setDataPath]=useState('');
  const [range,setRange]=useState<[string,string]>(()=>rangePreset('month')), [preset,setPreset]=useState('month'), [query,setQuery]=useState('');
  const [form,setForm]=useState<Form|null>(null), [formError,setFormError]=useState(''), [deleting,setDeleting]=useState<Entry|null>(null), [restore,setRestore]=useState(false), [rateInput,setRateInput]=useState(''), [nameInput,setNameInput]=useState('');
  function adopt(s:State){current.current=s;setState(s)}
  useEffect(()=>{let alive=true; (async()=>{try{const result=window.desktop?await window.desktop.load():{state:JSON.parse(localStorage.getItem('kaarnegar')||'null')||emptyState,warning:'',dataPath:'ذخیره در همین مرورگر'};if(alive){adopt(result.state);setRateInput(String(result.state.rate||''));setNameInput(result.state.name);setWarning(result.warning);setDataPath(result.dataPath);setLoaded(true)}}catch{if(alive)setError('اطلاعات بارگیری نشد. برنامه را دوباره باز کنید.')}})();const off=window.desktop?.onState(s=>{adopt(s);setWarning('زمان‌سنج به صورت خودکار مکث شد.')});return()=>{alive=false;off?.()}},[]);
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id)},[toast]);
  async function commit(next:State, message='') {
    if(lock.current)return false;lock.current=true;setBusy(true);
    try{if(window.desktop)await window.desktop.save(next);else localStorage.setItem('kaarnegar',JSON.stringify(next));adopt(next);if(message)setToast(message);setError('');return true}catch{setError('ذخیره انجام نشد. فضای دیسک و دسترسی برنامه را بررسی کنید.');return false}finally{lock.current=false;setBusy(false)}
  }
  useEffect(()=>{const id=setInterval(()=>{const s=current.current;if(s.active?.runningSince!=null&&!lock.current)void commit({...s,active:checkpoint(s.active)})},15000);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!window.desktop){const save=()=>{const s=current.current;if(s.active)localStorage.setItem('kaarnegar',JSON.stringify({...s,active:pauseActive(s.active)}))};window.addEventListener('beforeunload',save);return()=>window.removeEventListener('beforeunload',save)}},[]);
  const a=state.active, elapsed=activeDuration(a,now), running=a?.runningSince!=null;
  const today=localDate(), todayEntries=state.entries.filter(e=>e.date===today), todayTotal=totals(todayEntries), monthTotal=totals(filtered(state.entries,...rangePreset('month')));
  const validRange=range[0]<=range[1], reportEntries=validRange?filtered(state.entries,...range,query):[], report=totals(reportEntries), groups=groupTasks(reportEntries);
  const recent=[...state.entries].sort((x,y)=>y.date.localeCompare(x.date)||y.createdAt-x.createdAt).slice(0,8);
  const dates=[...new Set((page==='reports'?reportEntries:recent).map(e=>e.date))];
  function choosePreset(p:string){setPreset(p);setRange(rangePreset(p))}
  async function start(){if(a||busy)return;if(!title.trim()){setError('برای شروع، عنوان فعالیت را وارد کنید.');return}await commit({...state,active:{id:crypto.randomUUID(),title:title.trim(),rate:state.rate,segments:[],runningSince:Date.now()}});}
  async function toggle(){if(!a)return;await commit({...state,active:running?pauseActive(a):{...a,runningSince:Date.now()}},running?'زمان‌سنج مکث شد.':'زمان‌سنج ادامه پیدا کرد.')}
  async function stop(){if(!a)return;const entries=finishActive(a);if(await commit({...state,active:null,entries:[...state.entries,...entries]},entries.length?'زمان فعالیت ذخیره شد.':'زمان‌سنج متوقف شد.'))setTitle('')}
  async function widget(){try{if(window.desktop)await window.desktop.widget(!compact);setCompact(!compact)}catch{setError('حالت ویجت باز نشد.')}}
  function openManual(e?:Entry){setFormError('');setForm(e?{id:e.id,title:e.title,date:e.date,hours:String(Math.floor(e.durationMs/3600000)),minutes:String(Math.floor(e.durationMs/60000)%60),seconds:String(Math.floor(e.durationMs/1000)%60),rate:String(e.rate)}:{title:'',date:today,hours:'',minutes:'',seconds:'',rate:String(state.rate||'')})}
  async function submitEntry(e:FormEvent){e.preventDefault();if(!form)return;const h=Number(latin(form.hours)),m=Number(latin(form.minutes)),s=Number(latin(form.seconds)),r=Number(latin(form.rate));const ms=(h*3600+m*60+s)*1000;if(!form.title.trim()||form.title.length>200||![h,m,s,r].every(Number.isFinite)||![h,m,s].every(Number.isInteger)||h<0||m<0||m>59||s<0||s>59||ms<=0||ms>86400000||r<0||r>1e12){setFormError('عنوان، زمان (حداکثر ۲۴ ساعت) و نرخ معتبر وارد کنید. دقیقه و ثانیه باید بین ۰ تا ۵۹ باشند.');return}const old=state.entries.find(e=>e.id===form.id);const item:Entry={id:form.id||crypto.randomUUID(),title:form.title.trim(),date:form.date,durationMs:ms,rate:r,source:old?.source||'manual',createdAt:old?.createdAt||Date.now()};if(await commit({...state,entries:[...state.entries.filter(e=>e.id!==item.id),item]},'زمان فعالیت ذخیره شد.'))setForm(null)}
  async function saveSettings(e:FormEvent){e.preventDefault();const r=Number(latin(rateInput));if(!Number.isFinite(r)||r<0||r>1e12){setError('نرخ ساعتی معتبر وارد کنید.');return}await commit({...state,rate:r,name:nameInput.trim()},'تنظیمات ذخیره شد.')}
  async function exportPDF(){if(!reportEntries.length||!validRange)return;setBusy(true);try{const html=reportHTML(reportEntries,...range,state.name);if(window.desktop){if(await window.desktop.exportPDF(html))setToast('گزارش PDF ذخیره شد.')}else{const w=window.open('','_blank');if(w){w.document.write(html);w.document.close();w.onload=()=>w.print()}}}catch{setError('گزارش ذخیره نشد. مسیر فایل را بررسی کنید.')}finally{setBusy(false)}}
  async function backup(){try{if(window.desktop){if(await window.desktop.backup())setToast('نسخهٔ پشتیبان ذخیره شد.')}else{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='kaarnegar-backup.json';link.click();URL.revokeObjectURL(url)}}catch{setError('نسخهٔ پشتیبان ذخیره نشد.')}}
  async function importBackup(){setRestore(false);try{const s=await window.desktop?.importBackup();if(s){adopt(s);setRateInput(String(s.rate));setNameInput(s.name);setToast('نسخهٔ پشتیبان بازیابی شد.')}}catch(e){setError(e instanceof Error?e.message:'فایل نسخهٔ پشتیبان معتبر نیست.')}}
  function timerCard(){return <section className={`timer-card ${running?'is-running':''}`}><div className="timer-top"><span className="eyebrow"><span className={`status-dot ${running?'live':''}`}/>{a?(running?'در حال ثبت زمان':'زمان‌سنج در حالت مکث'):'آماده برای یک شروع خوب'}</span><span className="timer-symbol"><Timer size={22}/></span></div><div className="timer-digits" dir="ltr">{duration(elapsed,true)}</div><p className="timer-subtitle">{a?`نرخ این فعالیت: ${number(a.rate)} تومان / ساعت`:'هر دقیقهٔ کار شما ارزشمند است.'}</p><div className="task-input"><Pencil size={18}/><input aria-label="عنوان فعالیت" placeholder="روی چه چیزی کار می‌کنید؟" maxLength={200} value={a?a.title:title} disabled={!!a||busy} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void start()}}/></div><div className="timer-actions">{a?<><button className="primary" onClick={toggle} disabled={busy}>{running?<Pause size={18}/>:<Play size={18}/>} {running?'مکث':'ادامهٔ فعالیت'}</button><button className="stop-button" onClick={stop} disabled={busy}><Square size={16} fill="currentColor"/> توقف و ذخیره</button></>:<button className="primary start" onClick={start} disabled={busy||!loaded}><Play size={18} fill="currentColor"/> شروع فعالیت <span>شروع یک تمرکز تازه</span></button>}</div>{!compact&&<div className="timer-footer"><span><ShieldCheck size={14}/> ذخیرهٔ خودکار روی دستگاه شما</span><span>{a?`${number(elapsed/3600000*a.rate)} تومان`:'بدون نیاز به اینترنت'}</span></div>}</section>}
  function entryRows(items:Entry[]){return items.map(e=><tr key={e.id}><td><div className="entry-title"><span className={`entry-icon ${e.source}`} >{e.source==='manual'?<Pencil size={16}/>:<Timer size={17}/>}</span><div><strong>{e.title}</strong><small>{e.source==='manual'?'ثبت دستی':'زمان‌سنج'}</small></div></div></td><td><span className="numeric" dir="ltr">{duration(e.durationMs,true)}</span></td><td>{number(e.rate)} <small>تومان</small></td><td className="amount">{number(e.durationMs/3600000*e.rate)} <small>تومان</small></td><td><div className="row-actions"><button className="icon-button" aria-label={`ویرایش ${e.title}`} onClick={()=>openManual(e)} disabled={busy}><Pencil size={15}/></button><button className="icon-button delete" aria-label={`حذف ${e.title}`} onClick={()=>setDeleting(e)} disabled={busy}><Trash2 size={15}/></button></div></td></tr>)}
  function entryTable(items:Entry[]){return <div className="table-scroll"><table className="entries-table"><thead><tr><th>فعالیت</th><th>مدت کار</th><th>نرخ ساعتی</th><th>درآمد</th><th></th></tr></thead><tbody>{entryRows(items)}</tbody></table></div>}
  function empty(){return <div className="empty"><span><Coffee size={30}/></span><h3>{page==='reports'?'زمانی در این بازه ثبت نشده':'اولین فعالیت خود را ثبت کنید'}</h3><p>{page==='reports'?'بازهٔ تاریخ یا عبارت جست‌وجو را تغییر دهید.':'با شروع زمان‌سنج یا ثبت دستی، مسیر کارتان را روشن کنید.'}</p>{page!=='reports'&&<button className="text-button" onClick={()=>openManual()}>ثبت دستی زمان <ArrowLeft size={15}/></button>}</div>}
  if(!loaded)return <div className="loading"><Timer size={36}/><p>{error||'کارنگار در حال آماده‌شدن است…'}</p></div>;
  return <div className={`${compact?'app compact':'app'}${window.desktop?' desktop-app':''}`}>
    <WindowBar/>
    {!compact&&<aside className="sidebar"><div className="brand"><span className="brand-mark"><Timer size={28}/></span><div><strong>کارنگار</strong><small>زمان شما، ارزش شما</small></div></div><span className="nav-label">فضای کاری شما</span><nav>{([{id:'timer',label:'ثبت زمان',icon:LayoutDashboard},{id:'reports',label:'گزارش‌ها',icon:BarChart3},{id:'settings',label:'تنظیمات',icon:Settings2}] as const).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setQuery('')}}><n.icon size={20}/>{n.label}{page===n.id&&<ChevronLeft size={16} className="nav-chevron"/>}</button>)}</nav><div className="sidebar-bottom"><div className="profile"><span className="avatar">{state.name?state.name.slice(0,1):'ک'}</span><div><strong>{state.name||'فضای کاری شخصی'}</strong><small>نسخهٔ دسکتاپ · ۱.۰</small></div><ShieldCheck size={18}/></div></div></aside>}
    <main>{compact?<div className="widget-heading"><div className="widget-brand"><Timer size={20}/> کارنگار</div><button className="icon-button" aria-label="نمای کامل" onClick={widget}><Maximize2 size={18}/></button></div>:<header className="topbar"><div className="breadcrumb">فضای کاری <ChevronLeft size={14}/><strong>{page==='timer'?'ثبت زمان':page==='reports'?'گزارش‌ها':'تنظیمات'}</strong></div><div className="topbar-right"><span><CalendarDays size={16}/>{dateLabel(today,true)}</span><button className="outline small" onClick={widget}><Minimize2 size={15}/> ویجت کوچک</button></div></header>}
    <div className="content">{!compact&&<div className="page-heading"><div><span className="eyebrow">{page==='timer'?'یک روز خوب، یک قدم جلوتر':page==='reports'?'تصویر روشن‌تری از کارتان':'کارنگار، به سبک شما'}</span><h1>{page==='timer'?'زمان خود را ارزشمند کنید.':page==='reports'?'گزارش زمان و درآمد':'تنظیمات فضای کاری'}</h1><p>{page==='timer'?'روی کارتان تمرکز کنید؛ حساب زمان با کارنگار.':page==='reports'?'ببینید زمانتان کجا صرف شده و چقدر ارزش داشته است.':'نرخ کار و اطلاعات شخصی خود را مدیریت کنید.'}</p></div>{page==='timer'?<button className="outline" onClick={()=>openManual()}><Plus size={18}/> ثبت دستی زمان</button>:page==='reports'?<button className="primary" disabled={busy||!reportEntries.length} onClick={exportPDF}><Download size={17}/> {busy?'در حال آماده‌سازی…':'دریافت گزارش PDF'}</button>:null}</div>}
    {warning&&!compact&&<div className="notice"><ShieldCheck size={18}/><span>{warning}</span><button className="icon-button" aria-label="بستن پیام" onClick={()=>setWarning('')}><X size={16}/></button></div>}
    {error&&<div className="error-banner" role="alert">{error}<button className="icon-button" aria-label="بستن خطا" onClick={()=>setError('')}><X size={16}/></button></div>}
    {(page==='timer'||compact)&&<>{!compact&&<div className="stats"><Stat icon={<Clock3 size={21}/>} label="زمان ثبت‌شدهٔ امروز" value={duration(todayTotal.ms,true)} suffix="ساعت : دقیقه : ثانیه" tone="teal"/><Stat icon={<Wallet size={21}/>} label="درآمد امروز" value={number(todayTotal.amount)} suffix="تومان" tone="purple"/><Stat icon={<CalendarDays size={21}/>} label="درآمد این ماه" value={number(monthTotal.amount)} suffix="تومان" tone="amber"/></div>}
    <div className="work-grid">{timerCard()}{!compact&&<section className="focus-card"><span className="eyebrow">با آرامش، با تمرکز</span><div className="focus-art"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="art-clock"><span className="hand long"/><span className="hand short"/><span className="clock-center"/><i className="tick t1"/><i className="tick t2"/><i className="tick t3"/><i className="tick t4"/></div><span className="art-spark s1">✦</span><span className="art-spark s2">✦</span><span className="art-pill"><Check size={13}/> یک قدم جلوتر</span></div><h3>کارهای بزرگ، دقیقه‌به‌دقیقه.</h3><p>زمان را ثبت کنید، پیشرفت را ببینید<br/>و برای کارتان ارزش قائل شوید.</p><button className="text-button" onClick={()=>{setPage('reports');choosePreset('month')}}>مرور گزارش این ماه <ArrowUpLeft size={16}/></button></section>}</div>
    {!compact&&<section className="card activities"><div className="section-heading"><div><h2>فعالیت‌های اخیر <span className="count">{number(state.entries.length)}</span></h2><p>ردپای کارهای شما، در یک نگاه</p></div><button className="text-button" onClick={()=>setPage('reports')}>مشاهدهٔ گزارش‌ها <ArrowLeft size={16}/></button></div>{recent.length?dates.map(date=><div className="day-group" key={date}><div className="day-heading"><span>{date===today?'امروز':dateLabel(date,true)}</span><span className="numeric" dir="ltr">{duration(totals(recent.filter(e=>e.date===date)).ms,true)}</span></div>{entryTable(recent.filter(e=>e.date===date))}</div>):empty()}</section>}</>}
    {page==='reports'&&!compact&&<><section className="card report-filters"><div className="preset-tabs">{[{id:'today',label:'امروز'},{id:'week',label:'این هفته'},{id:'month',label:'این ماه'}].map(p=><button className={preset===p.id?'selected':''} key={p.id} onClick={()=>choosePreset(p.id)}>{p.label}</button>)}<button className={preset==='custom'?'selected':''} onClick={()=>setPreset('custom')}>بازهٔ دلخواه</button></div><div className="filter-row"><DatePicker label="از تاریخ" value={range[0]} onChange={v=>{setRange([v,range[1]]);setPreset('custom')}}/><span className="date-divider">—</span><DatePicker label="تا تاریخ" value={range[1]} onChange={v=>{setRange([range[0],v]);setPreset('custom')}}/><label className="search"><Search size={18}/><input aria-label="جست‌وجوی فعالیت" placeholder="جست‌وجوی فعالیت…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{!validRange&&<p className="field-error">تاریخ پایان باید پس از تاریخ شروع یا برابر آن باشد.</p>}</section>
    <div className="stats"><Stat icon={<Clock3 size={21}/>} label="مجموع زمان کار" value={duration(report.ms,true)} suffix="ساعت : دقیقه : ثانیه" tone="teal"/><Stat icon={<Wallet size={21}/>} label="درآمد این بازه" value={number(report.amount)} suffix="تومان" tone="purple"/><Stat icon={<CheckCircle2 size={21}/>} label="فعالیت‌های انجام‌شده" value={number(report.tasks)} suffix={`${number(reportEntries.length)} ثبت زمان`} tone="amber"/></div>
    {reportEntries.length>0&&<div className="report-grid"><section className="card chart-card"><div className="section-heading"><div><h2>تقسیم زمان بین فعالیت‌ها</h2><p>سهم هر فعالیت از زمان ثبت‌شده</p></div><BarChart3 size={19}/></div><div className="task-bars">{groups.slice(0,5).map((g,i)=><div className="task-bar" key={g.title}><div><span><i style={{background:colors[i]}}/>{g.title}</span><strong className="numeric" dir="ltr">{duration(g.ms,true)}</strong></div><div className="bar-track"><span style={{width:`${g.ms/report.ms*100}%`,background:colors[i]}}/></div></div>)}</div>{groups.length>5&&<p className="muted">{number(groups.length-5)} فعالیت دیگر در جدول جزئیات و PDF</p>}</section><section className="card report-note"><span className="note-icon"><FileText size={26}/></span><h3>گزارشی برای ارائه</h3><p>جزئیات فعالیت‌ها، زمان کار و مبلغ نهایی؛ با تاریخ شمسی و فونت فارسی.</p><button className="outline" disabled={busy} onClick={exportPDF}><ArrowDownToLine size={16}/> خروجی PDF</button><small>مبلغ هر ثبت بر اساس نرخ همان فعالیت محاسبه می‌شود.</small></section></div>}
    <section className="card activities"><div className="section-heading"><div><h2>جزئیات فعالیت‌ها <span className="count">{number(reportEntries.length)}</span></h2><p>{dateLabel(range[0],true)} تا {dateLabel(range[1],true)}</p></div><button className="text-button" onClick={()=>openManual()}><Plus size={16}/> ثبت زمان</button></div>{reportEntries.length?dates.map(date=><div className="day-group" key={date}><div className="day-heading"><span>{dateLabel(date,true)}</span><span>{number(totals(reportEntries.filter(e=>e.date===date)).amount)} تومان</span></div>{entryTable(reportEntries.filter(e=>e.date===date))}</div>):empty()}{reportEntries.length>0&&<div className="report-total"><strong>جمع کل این بازه</strong><span className="numeric" dir="ltr">{duration(report.ms,true)}</span><strong>{number(report.amount)} <small>تومان</small></strong></div>}</section><p className="report-footnote">مبالغ به نزدیک‌ترین تومان گرد می‌شوند. زمان فعالیت در حال اجرا پس از «توقف و ذخیره» وارد گزارش می‌شود.</p></>}
    {page==='settings'&&!compact&&<div className="settings-grid"><section className="card settings-card"><div className="section-heading"><div><h2>مشخصات و نرخ ساعتی</h2><p>ارزش یک ساعت از زمان شما</p></div><Wallet size={22}/></div><form onSubmit={saveSettings}><label className="form-label">نام شما <input maxLength={100} placeholder="نام و نام خانوادگی" value={nameInput} onChange={e=>setNameInput(e.target.value)}/></label><label className="form-label">دستمزد ساعتی (تومان / IRT)<div className="suffix-input"><input aria-label="دستمزد ساعتی" inputMode="decimal" placeholder="مثلاً ۲۵۰۰۰۰" value={rateInput} onChange={e=>setRateInput(e.target.value)}/><span>تومان</span></div></label><div className="settings-hint"><ShieldCheck size={19}/><p>نرخ جدید برای فعالیت‌های بعدی استفاده می‌شود. نرخ فعالیت‌های قبلی و زمان‌سنج جاری حفظ می‌شود؛ برای تغییر آن‌ها، هر ثبت را ویرایش کنید.</p></div><button className="primary" type="submit" disabled={busy}><Check size={18}/> ذخیرهٔ تنظیمات</button></form></section><section className="card settings-card"><div className="section-heading"><div><h2>اطلاعات شما، در اختیار شما</h2><p>پشتیبان‌گیری و بازیابی</p></div><ShieldCheck size={22}/></div><p className="settings-description">اطلاعات فقط روی همین دستگاه ذخیره می‌شود. با گرفتن نسخهٔ پشتیبان، فعالیت‌ها و تنظیمات خود را نگه دارید یا به دستگاه دیگری منتقل کنید.</p><button className="outline full" onClick={backup}><Download size={18}/> دریافت نسخهٔ پشتیبان</button><button className="outline full" disabled={!!a||!window.desktop} onClick={()=>setRestore(true)}><Upload size={18}/> بازیابی از فایل</button>{a&&<small className="muted">برای بازیابی، ابتدا زمان‌سنج را متوقف و ذخیره کنید.</small>}<div className="storage-path"><span>محل ذخیرهٔ اطلاعات</span><code dir="ltr">{dataPath}</code></div><div className="settings-hint"><Pause size={18}/><p>بستن پنجره، برنامه را به سینی سیستم می‌برد و زمان‌سنج ادامه پیدا می‌کند. برای خروج کامل، روی آیکون کنار ساعت راست‌کلیک و «خروج از برنامه» را انتخاب کنید. خواب دستگاه، زمان‌سنج را مکث می‌کند.</p></div></section></div>}
    {!compact&&<footer className="app-footer"><span>کارنگار · زمان شما، ارزش شما</span><span><span className="status-dot"/> {busy?'در حال ذخیره…':'ذخیره‌شده روی دستگاه'}</span></footer>}</div></main>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}
    {form&&<Modal title={form.id?'ویرایش ثبت زمان':'ثبت دستی زمان'} close={()=>{if(!busy)setForm(null)}}><form onSubmit={submitEntry}><p className="modal-description">زمان کارتان را با تاریخ شمسی و نرخ ساعتی ثبت کنید.</p><label className="form-label">عنوان فعالیت<input aria-label="عنوان ثبت دستی" autoFocus maxLength={200} placeholder="مثلاً طراحی صفحهٔ اصلی" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><DatePicker label="تاریخ فعالیت" value={form.date} onChange={v=>setForm({...form,date:v})}/><span className="form-label duration-label">مدت کار</span><div className="duration-inputs">{([{key:'hours',label:'ساعت'},{key:'minutes',label:'دقیقه'},{key:'seconds',label:'ثانیه'}] as const).map(f=><label key={f.key}><input aria-label={f.label} inputMode="numeric" placeholder="۰" value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})}/><span>{f.label}</span></label>)}</div><label className="form-label">نرخ ساعتی (تومان)<input aria-label="نرخ ثبت دستی" inputMode="decimal" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><div className="manual-total"><span>مبلغ این فعالیت</span><strong>{number(Math.max(0,((Number(latin(form.hours))||0)+(Number(latin(form.minutes))||0)/60+(Number(latin(form.seconds))||0)/3600)*(Number(latin(form.rate))||0)))} تومان</strong></div>{formError&&<p className="field-error" role="alert">{formError}</p>}<div className="modal-actions"><button className="primary" type="submit" disabled={busy}><Check size={18}/> ذخیرهٔ زمان</button><button className="outline" type="button" disabled={busy} onClick={()=>setForm(null)}>انصراف</button></div></form></Modal>}
    {deleting&&<Modal title="حذف ثبت زمان" close={()=>setDeleting(null)}><p className="modal-description">ثبت «{deleting.title}» به مدت <b dir="ltr">{duration(deleting.durationMs,true)}</b> حذف شود؟</p><div className="modal-actions"><button className="danger-button" disabled={busy} onClick={async()=>{if(await commit({...state,entries:state.entries.filter(e=>e.id!==deleting.id)},'ثبت زمان حذف شد.'))setDeleting(null)}}><Trash2 size={17}/> حذف ثبت</button><button className="outline" onClick={()=>setDeleting(null)}>انصراف</button></div></Modal>}
    {restore&&<Modal title="بازیابی نسخهٔ پشتیبان" close={()=>setRestore(false)}><p className="modal-description">فعالیت‌ها و تنظیمات فعلی با اطلاعات فایل انتخابی جایگزین می‌شوند. قبل از بازیابی، نسخهٔ پشتیبان فعلی را دریافت کنید.</p><div className="modal-actions"><button className="primary" onClick={importBackup}><Upload size={17}/> انتخاب فایل و بازیابی</button><button className="outline" onClick={()=>setRestore(false)}>انصراف</button></div></Modal>}
  </div>;
}
function Stat({icon,label,value,suffix,tone}:{icon:ReactNode;label:string;value:string;suffix:string;tone:string}) {return <section className="stat card"><div><span className="stat-label">{label}</span><div className="stat-value"><strong className="numeric" dir="ltr">{value}</strong></div><small>{suffix}</small></div><span className={`stat-icon ${tone}`}>{icon}</span></section>}
