import { t, setLanguage } from './i18n';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowUpLeft, BarChart3, CalendarDays, Check, CheckCircle2, ChevronLeft, Clock3, Coffee, Download, FileText, LayoutDashboard, Maximize2, Minimize2, Pause, Pencil, Play, Plus, Search, Settings2, ShieldCheck, Square, Timer, Trash2, Upload, Wallet, X } from 'lucide-react';
import type { Preferences } from './global';
import WorkspaceSettings, { AssignmentFields } from './WorkspaceSettings';
import DatePicker from './DatePicker';
import WindowControls from './WindowControls';
import TaskTitleInput from './TaskTitleInput';
import { activeDuration, effectiveRate, migrateState, money, moneySummary, checkpoint, dateLabel, digits, duration, emptyState, filtered, fromDate, finishActive, groupTasks, latin, localDate, number, pauseActive, rangePreset, totals, type Entry, type State } from './model';
import { reportFilename, reportHTML } from './report';
import { activeStart, changeActiveStart, clockTime, clockTimestamp, entrySegments, retimeSegments, segmentDuration, type Segment } from './model';
type Page = 'timer'|'reports'|'settings';
type Form = { id?:string; title:string; date:string; endDate:string; startTime:string; endTime:string; rate:string; organizationId:string; projectId:string; currency:import('./model').Currency };
function formInterval(form:Form,old?:Entry):{start:number;end:number;segments:Segment[];ms:number} {
  let start=clockTimestamp(form.date,form.startTime),end=clockTimestamp(form.endDate,form.endTime);
  const original=old?entrySegments(old):[],first=original[0],last=original.at(-1);
  const shift=first?clockTimestamp(form.date,clockTime(first.start))-clockTimestamp(localDate(new Date(first.start)),clockTime(first.start)):0;
  if(first&&form.startTime===clockTime(first.start))start=first.start+shift;
  if(last&&form.endTime===clockTime(last.end)&&form.endDate===localDate(new Date(last.end+shift)))end=last.end+shift;
  const valid=Number.isFinite(start)&&Number.isFinite(end)&&end>start;
  const segments=valid?retimeSegments(original.map(s=>({start:s.start+shift,end:s.end+shift})),start,end):[];
  return {start,end,segments,ms:segmentDuration(segments)};
}
const colors=['#168b78','#7c6cc8','#d69c48','#598dc7','#c87883'];
function Modal({ title, children, close }: {title:string;children:ReactNode;close:()=>void}) {
  const box=useRef<HTMLDivElement>(null), closeRef=useRef(close);closeRef.current=close;
  useEffect(()=>{ const old=document.activeElement as HTMLElement; box.current?.querySelector<HTMLInputElement>('input')?.focus(); if(!box.current?.contains(document.activeElement))box.current?.focus(); const key=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const els=box.current?.querySelectorAll<HTMLElement>('button,input,select,[tabindex="0"]'); if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);old?.focus()}},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label={t("بستن")} onClick={close}><X size={20}/></button></div>{children}</div></div>;
}
export default function App() {
  const [state,setState]=useState<State>(emptyState), current=useRef(state), [loaded,setLoaded]=useState(false), [busy,setBusy]=useState(false), lock=useRef(false);
  const [page,setPage]=useState<Page>('timer'), [now,setNow]=useState(Date.now()), [title,setTitle]=useState(''), [compact,setCompact]=useState(false), [toast,setToast]=useState(''), [error,setError]=useState(''), [warning,setWarning]=useState(''), [dataPath,setDataPath]=useState('');
  const [range,setRange]=useState<[string,string]>(()=>rangePreset('month')), [preset,setPreset]=useState('month'), [query,setQuery]=useState('');
  const [form,setForm]=useState<Form|null>(null), [formError,setFormError]=useState(''), [deleting,setDeleting]=useState<Entry|null>(null), [restore,setRestore]=useState(false), [rateInput,setRateInput]=useState(''), [nameInput,setNameInput]=useState('');
  const [preferences,setPreferences]=useState<Preferences>({theme:'system',language:'en',launchOnStartup:false,compact:false}), [preferencesBusy,setPreferencesBusy]=useState(false), preferencesLock=useRef(false);
  const [organizationId,setOrganizationId]=useState(''), [projectId,setProjectId]=useState(''), [reportOrg,setReportOrg]=useState(''), [reportProject,setReportProject]=useState('');
  const [startForm,setStartForm]=useState<{id:string;date:string;time:string}|null>(null),[startError,setStartError]=useState('');
  useEffect(()=>{
    if(organizationId&&!state.organizations.some(o=>o.id===organizationId)){setOrganizationId('');setProjectId('')}
    else if(projectId&&!state.projects.some(p=>p.id===projectId&&p.organizationId===organizationId))setProjectId('');
    if(reportOrg&&!state.organizations.some(o=>o.id===reportOrg)){setReportOrg('');setReportProject('')}
    else if(reportProject&&!state.projects.some(p=>p.id===reportProject&&(!reportOrg||p.organizationId===reportOrg)))setReportProject('');
  },[state.organizations,state.projects,organizationId,projectId,reportOrg,reportProject]);
  setLanguage(preferences.language);
  useEffect(()=>{document.documentElement.lang=preferences.language;document.title=t("کارنگار");document.documentElement.dir=preferences.language==='en'?'ltr':'rtl';if(preset!=='custom')setRange(rangePreset(preset))},[preferences.language]);
  function adopt(s:State){const next=migrateState(s);current.current=next;setState(next)}
  useEffect(()=>{let alive=true; (async()=>{try{const result=window.desktop?await window.desktop.load():{state:JSON.parse(localStorage.getItem('kaarnegar')||'null')||emptyState,preferences:{theme:'system',language:'en',launchOnStartup:false,compact:false,...JSON.parse(localStorage.getItem('kaarnegar-preferences')||'{}')},warning:'',dataPath:t("ذخیره در همین مرورگر")};if(alive){adopt(result.state);setPreferences(result.preferences);setCompact(result.preferences.compact);setRateInput(String(result.state.rate||''));setNameInput(result.state.name);setWarning(result.warning);setDataPath(result.dataPath);setLoaded(true)}}catch{if(alive)setError(t("اطلاعات بارگیری نشد. برنامه را دوباره باز کنید."))}})();const off=window.desktop?.onState(s=>{adopt(s);setWarning(t("زمان‌سنج به صورت خودکار مکث شد."))});return()=>{alive=false;off?.()}},[]);
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id)},[toast]);
  useEffect(()=>{
    const media=window.matchMedia('(prefers-color-scheme: dark)');
    const apply=()=>{document.documentElement.dataset.theme=preferences.theme==='system'?(media.matches?'dark':'light'):preferences.theme};
    apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);
  },[preferences.theme]);
  async function updatePreferences(patch:Partial<Pick<Preferences,'theme'|'launchOnStartup'|'language'>>){
    if(preferencesLock.current)return;preferencesLock.current=true;setPreferencesBusy(true);
    const previous=preferences,next={...preferences,...patch};setPreferences(next);
    try{if(window.desktop)setPreferences(await window.desktop.savePreferences(next));else localStorage.setItem('kaarnegar-preferences',JSON.stringify(next));setError('');setToast(t("تنظیمات ذخیره شد."))}
    catch{setPreferences(previous);setError(t("ذخیرهٔ تنظیمات برنامه انجام نشد. دسترسی به فایل‌ها و تنظیمات راه‌اندازی ویندوز را بررسی کنید."))}
    finally{preferencesLock.current=false;setPreferencesBusy(false)}
  }
  async function commit(next:State, message='') {
    if(lock.current)return false;lock.current=true;setBusy(true);
    try{if(window.desktop)await window.desktop.save(next);else localStorage.setItem('kaarnegar',JSON.stringify(next));adopt(next);if(message)setToast(message);setError('');return true}catch{setError(t("ذخیره انجام نشد. فضای دیسک و دسترسی برنامه را بررسی کنید."));return false}finally{lock.current=false;setBusy(false)}
  }
  useEffect(()=>{const id=setInterval(()=>{const s=current.current;if(s.active?.runningSince!=null&&!lock.current)void commit({...s,active:checkpoint(s.active)})},15000);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!window.desktop){const save=()=>{const s=current.current;if(s.active)localStorage.setItem('kaarnegar',JSON.stringify({...s,active:pauseActive(s.active)}))};window.addEventListener('beforeunload',save);return()=>window.removeEventListener('beforeunload',save)}},[]);
  const a=state.active, elapsed=activeDuration(a,now), running=a?.runningSince!=null;
  const today=localDate(), todayEntries=state.entries.filter(e=>e.date===today), todayTotal=totals(todayEntries), monthTotal=totals(filtered(state.entries,...rangePreset('month')));
  const validRange=range[0]<=range[1], reportEntries=validRange?filtered(state.entries,...range,query,reportOrg,reportProject):[], report=totals(reportEntries), groups=groupTasks(reportEntries);
  const recent=[...state.entries].sort((x,y)=>y.date.localeCompare(x.date)||y.createdAt-x.createdAt).slice(0,8);
  const dates=[...new Set((page==='reports'?reportEntries:recent).map(e=>e.date))];
  function choosePreset(p:string){setPreset(p);setRange(rangePreset(p))}
  async function start(){if(a||busy)return;if(!title.trim()){setError(t("برای شروع، عنوان فعالیت را وارد کنید."));return}if(!state.organizations.some(o=>o.id===organizationId)){setError(t('Select an organization before starting.'));return}
    await commit({...state,active:{id:crypto.randomUUID(),title:title.trim(),organizationId,projectId:projectId||null,currency:state.organizations.find(o=>o.id===organizationId)!.currency,rate:effectiveRate(state,organizationId,projectId||null),segments:[],runningSince:Date.now()}});
  }
  async function toggle(){if(!a)return;await commit({...state,active:running?pauseActive(a):{...a,runningSince:Date.now()}},running?t("زمان‌سنج مکث شد."):t("زمان‌سنج ادامه پیدا کرد."))}
  async function stop(){if(!a)return;const entries=finishActive(a);if(await commit({...state,active:null,entries:[...state.entries,...entries]},entries.length?t("زمان فعالیت ذخیره شد."):t("زمان‌سنج متوقف شد.")))setTitle('')}
  async function widget(){try{if(window.desktop)setCompact(await window.desktop.widget(!compact));else {const next=!compact;localStorage.setItem('kaarnegar-preferences',JSON.stringify({...preferences,compact:next}));setCompact(next);setPreferences({...preferences,compact:next})}}catch{setError(t("حالت ویجت باز نشد."))}}
  function openManual(e?:Entry){
    setFormError('');const org=e?.organizationId||organizationId,project=e?e.projectId||'':projectId;
    const segments=e?entrySegments(e):[{start:Date.now()-3600000,end:Date.now()}],start=segments[0].start,end=segments.at(-1)!.end;
    setForm({id:e?.id,title:e?.title||'',date:localDate(new Date(start)),endDate:localDate(new Date(end)),startTime:clockTime(start),endTime:clockTime(end),rate:e?String(e.rate):org?String(effectiveRate(state,org,project||null)):'',organizationId:org,projectId:project,currency:e?.currency??state.organizations.find(o=>o.id===org)?.currency??'IRT'});
  }
  function chooseTask(entry:Entry){setTitle(entry.title);setOrganizationId(entry.organizationId||'');setProjectId(entry.projectId||'')}
  function assignForm(org:string,project:string,taskTitle=form?.title){if(form)setForm({...form,title:taskTitle??'',organizationId:org,projectId:project,currency:state.organizations.find(o=>o.id===org)?.currency??'IRT',rate:org?String(effectiveRate(state,org,project||null)):''})}
  async function submitEntry(e:FormEvent){
    e.preventDefault();if(!form)return;
    if(!state.organizations.some(o=>o.id===form.organizationId)){setFormError(t('Select an organization for this entry.'));return}
    const old=state.entries.find(e=>e.id===form.id),interval=formInterval(form,old),r=Number(latin(form.rate));
    if(!form.title.trim()||form.title.length>200||!Number.isFinite(r)||r<0||r>1e12){setFormError(t('Enter a task title and a valid hourly rate.'));return}
    if(!Number.isFinite(interval.start)||!Number.isFinite(interval.end)||interval.end<=interval.start||interval.ms<=0||interval.ms>86400000){setFormError(t('Enter a valid start and end time, with up to 24 hours of work.'));return}
    const item:Entry={id:form.id||crypto.randomUUID(),title:form.title.trim(),date:form.date,durationMs:interval.ms,segments:interval.segments,rate:r,organizationId:form.organizationId,projectId:form.projectId||null,currency:form.currency,source:old?.source||'manual',createdAt:old?.createdAt||Date.now()};
    if(await commit({...state,entries:[...state.entries.filter(e=>e.id!==item.id),item]},t("زمان فعالیت ذخیره شد.")))setForm(null);
  }
  function openStart(){if(!a)return;const start=activeStart(a);if(start===null)return;setStartError('');setStartForm({id:a.id,date:localDate(new Date(start)),time:clockTime(start)})}
  async function submitStart(e:FormEvent){
    e.preventDefault();if(!startForm)return;
    const s=current.current,active=s.active;
    if(!active||active.id!==startForm.id){setStartError(t('This timer is no longer active.'));return}
    try{
      const original=activeStart(active);
      const start=original!==null&&startForm.date===localDate(new Date(original))&&startForm.time===clockTime(original)?original:clockTimestamp(startForm.date,startForm.time);
      if(await commit({...s,active:changeActiveStart(active,start)},t('Timer start time saved.')))setStartForm(null);
    }catch(error){setStartError(t(error instanceof Error?error.message:'Enter a valid start time.'))}
  }
  async function saveSettings(e:FormEvent){e.preventDefault();const r=Number(latin(rateInput));if(!Number.isFinite(r)||r<0||r>1e12){setError(t("نرخ ساعتی معتبر وارد کنید."));return}await commit({...state,rate:r,name:nameInput.trim()},t("تنظیمات ذخیره شد."))}
  async function exportPDF(){if(!reportEntries.length||!validRange)return;setBusy(true);try{const html=reportHTML(reportEntries,...range,state.name,{language:preferences.language,organizations:state.organizations,projects:state.projects,organizationId:reportOrg,projectId:reportProject});const filename=reportFilename(...range,preferences.language);if(window.desktop){if(await window.desktop.exportPDF(html,filename))setToast(t("گزارش PDF ذخیره شد."))}else{const w=window.open('','_blank');if(w){w.document.write(html);w.document.title=filename;w.document.close();w.onload=()=>w.print()}}}catch{setError(t("گزارش ذخیره نشد. مسیر فایل را بررسی کنید."))}finally{setBusy(false)}}
  async function backup(){try{if(window.desktop){if(await window.desktop.backup())setToast(t("نسخهٔ پشتیبان ذخیره شد."))}else{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='kaarnegar-backup.json';link.click();URL.revokeObjectURL(url)}}catch{setError(t("نسخهٔ پشتیبان ذخیره نشد."))}}
  async function importBackup(){setRestore(false);try{const s=await window.desktop?.importBackup();if(s){adopt(s);setRateInput(String(s.rate));setNameInput(s.name);setToast(t("نسخهٔ پشتیبان بازیابی شد."))}}catch(e){setError(e instanceof Error?e.message:t("فایل نسخهٔ پشتیبان معتبر نیست."))}}
  function timerCard(){return <section className={`timer-card ${running?'is-running':''}`}><div className="timer-top"><span className="eyebrow"><span className={`status-dot ${running?'live':''}`}/>{a?(running?t("در حال ثبت زمان"):t("زمان‌سنج در حالت مکث")):t("آماده برای یک شروع خوب")}</span><span className="timer-symbol"><Timer size={22}/></span></div><div className="timer-digits" dir="ltr">{duration(elapsed,true)}</div><p className="timer-subtitle">{a?t('Rate: {0} / hour',money(a.rate,a.currency)):t("هر دقیقهٔ کار شما ارزشمند است.")}</p><TaskTitleInput state={state} label={t("عنوان فعالیت")} placeholder={t("روی چه چیزی کار می‌کنید؟")} value={a?a.title:title} disabled={!!a||busy} onChange={setTitle} onSelect={chooseTask} onEnter={()=>void start()}/>{!a?<><AssignmentFields state={state} organizationId={organizationId} projectId={projectId} disabled={busy} onChange={(org,project)=>{setOrganizationId(org);setProjectId(project)}}/>{!state.organizations.length&&<button className="text-button" onClick={()=>{setPage('settings');if(compact)void widget()}}>{t('Manage organizations')}</button>}</>:<p className="task-assignment">{state.organizations.find(o=>o.id===a.organizationId)?.name}{a.projectId?' / '+state.projects.find(p=>p.id===a.projectId)?.name:''}</p>}{a&&activeStart(a)!==null&&<button className="timer-start-time text-button" onClick={openStart} disabled={busy} aria-label={t('Edit timer start time')}><Clock3 size={14}/><span>{t('Started at')} <bdi>{digits(clockTime(activeStart(a)!))}</bdi> · {dateLabel(localDate(new Date(activeStart(a)!)))}</span><Pencil size={13}/></button>}<div className="timer-actions">{a?<><button className="primary" onClick={toggle} disabled={busy}>{running?<Pause size={18}/>:<Play size={18}/>} {running?t("مکث"):t("ادامهٔ فعالیت")}</button><button className="stop-button" onClick={stop} disabled={busy}><Square size={16} fill="currentColor"/>{t("توقف و ذخیره")}</button></>:<button className="primary start" onClick={start} disabled={busy||!loaded}><Play size={18} fill="currentColor"/>{t("شروع فعالیت")}{' '}<span>{t("شروع یک تمرکز تازه")}</span></button>}</div>{!compact&&<div className="timer-footer"><span><ShieldCheck size={14}/>{t("ذخیرهٔ خودکار روی دستگاه شما")}</span>{a&&<span>{money(elapsed/3600000*a.rate,a.currency)}</span>}</div>}</section>}
  function entryRows(items:Entry[]){return items.map(e=><tr key={e.id}><td><div className="entry-title"><span className={`entry-icon ${e.source}`} >{e.source==='manual'?<Pencil size={16}/>:<Timer size={17}/>}</span><div><strong>{e.title}</strong><small className="entry-assignment">{state.organizations.find(o=>o.id===e.organizationId)?.name}{e.projectId?' / '+state.projects.find(p=>p.id===e.projectId)?.name:''}</small><small>{e.source==='manual'?t("ثبت دستی"):t("زمان‌سنج")}</small></div></div></td><td><span className="numeric" dir="ltr">{duration(e.durationMs,true)}</span>{e.segments?.length?<small className="entry-clock" dir="ltr">{digits(clockTime(e.segments[0].start))} – {digits(clockTime(e.segments.at(-1)!.end))}{localDate(new Date(e.segments.at(-1)!.end))!==e.date?<span> · {dateLabel(localDate(new Date(e.segments.at(-1)!.end)))}</span>:null}</small>:null}</td><td>{money(e.rate,e.currency)}</td><td className="amount">{money(e.durationMs/3600000*e.rate,e.currency)}</td><td><div className="row-actions"><button className="icon-button" aria-label={t("ویرایش {0}",e.title)} onClick={()=>openManual(e)} disabled={busy}><Pencil size={15}/></button><button className="icon-button delete" aria-label={t("حذف {0}",e.title)} onClick={()=>setDeleting(e)} disabled={busy}><Trash2 size={15}/></button></div></td></tr>)}
  function entryTable(items:Entry[]){return <div className="table-scroll"><table className="entries-table"><thead><tr><th>{t("فعالیت")}</th><th>{t("مدت کار")}</th><th>{t("نرخ ساعتی")}</th><th>{t("درآمد")}</th><th></th></tr></thead><tbody>{entryRows(items)}</tbody></table></div>}
  function empty(){return <div className="empty"><span><Coffee size={30}/></span><h3>{page==='reports'?t("زمانی در این بازه ثبت نشده"):t("اولین فعالیت خود را ثبت کنید")}</h3><p>{page==='reports'?t("بازهٔ تاریخ یا عبارت جست‌وجو را تغییر دهید."):t("با شروع زمان‌سنج یا ثبت دستی، مسیر کارتان را روشن کنید.")}</p>{page!=='reports'&&<button className="text-button" onClick={()=>openManual()}>{t("ثبت دستی زمان")}{' '}<ArrowLeft size={15}/></button>}</div>}
  if(!loaded)return <div className="loading"><Timer size={36}/><p>{error||t("کارنگار در حال آماده‌شدن است…")}</p></div>;
  return <div className={`${compact?'app compact':'app'}${window.desktop?' desktop-app':''}`}>
    {!compact&&<aside className="sidebar"><div className="brand"><span className="brand-mark"><Timer size={28}/></span><div><strong>{t("کارنگار")}</strong><small>{t("زمان شما، ارزش شما")}</small></div></div><span className="nav-label">{t("فضای کاری شما")}</span><nav>{([{id:'timer',label:t("ثبت زمان"),icon:LayoutDashboard},{id:'reports',label:t("گزارش‌ها"),icon:BarChart3},{id:'settings',label:t("تنظیمات"),icon:Settings2}] as const).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setQuery('')}}><n.icon size={20}/>{n.label}{page===n.id&&<ChevronLeft size={16} className="nav-chevron"/>}</button>)}</nav><div className="sidebar-bottom"><div className="profile"><span className="avatar">{state.name?state.name.slice(0,1):t("ک")}</span><div><strong>{state.name||t("فضای کاری شخصی")}</strong><small>{t("نسخهٔ دسکتاپ · ۱.۰")}</small></div><ShieldCheck size={18}/></div></div></aside>}
    <main>{compact?<div className="widget-heading"><div className="widget-brand"><Timer size={20}/>{t("کارنگار")}</div><WindowControls compact={compact} onWidget={widget}/></div>:<header className="topbar"><div className="breadcrumb">{t("فضای کاری")}{' '}<ChevronLeft size={14}/><strong>{page==='timer'?t("ثبت زمان"):page==='reports'?t("گزارش‌ها"):t("تنظیمات")}</strong></div><WindowControls compact={compact} onWidget={widget}/></header>}
    <div className="content">{!compact&&<div className="page-heading"><div><span className="eyebrow">{page==='timer'?t("یک روز خوب، یک قدم جلوتر"):page==='reports'?t("تصویر روشن‌تری از کارتان"):t("کارنگار، به سبک شما")}</span><h1>{page==='timer'?t("زمان خود را ارزشمند کنید."):page==='reports'?t("گزارش زمان و درآمد"):t("تنظیمات فضای کاری")}</h1><p>{page==='timer'?t("روی کارتان تمرکز کنید؛ حساب زمان با کارنگار."):page==='reports'?t("ببینید زمانتان کجا صرف شده و چقدر ارزش داشته است."):t("نرخ کار و اطلاعات شخصی خود را مدیریت کنید.")}</p></div>{page==='timer'?<button className="outline" onClick={()=>openManual()}><Plus size={18}/>{t("ثبت دستی زمان")}</button>:page==='reports'?<button className="primary" disabled={busy||!reportEntries.length} onClick={exportPDF}><Download size={17}/> {busy?t("در حال آماده‌سازی…"):t("دریافت گزارش PDF")}</button>:null}</div>}
    {warning&&!compact&&<div className="notice"><ShieldCheck size={18}/><span>{t(warning)}</span><button className="icon-button" aria-label={t("بستن پیام")} onClick={()=>setWarning('')}><X size={16}/></button></div>}
    {error&&<div className="error-banner" role="alert">{t(error)}<button className="icon-button" aria-label={t("بستن خطا")} onClick={()=>setError('')}><X size={16}/></button></div>}
    {(page==='timer'||compact)&&<>{!compact&&<div className="stats"><Stat icon={<Clock3 size={21}/>} label={t("زمان ثبت‌شدهٔ امروز")} value={duration(todayTotal.ms,true)} suffix={t("ساعت : دقیقه : ثانیه")} tone="teal"/><Stat icon={<Wallet size={21}/>} label={t("درآمد امروز")} value={moneySummary(todayEntries)} suffix="" tone="purple"/><Stat icon={<CalendarDays size={21}/>} label={t("درآمد این ماه")} value={moneySummary(filtered(state.entries,...rangePreset('month')))} suffix="" tone="amber"/></div>}
    <div className="work-grid">{timerCard()}{!compact&&<section className="focus-card"><span className="eyebrow">{t("با آرامش، با تمرکز")}</span><div className="focus-art"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="art-clock"><span className="hand long"/><span className="hand short"/><span className="clock-center"/><i className="tick t1"/><i className="tick t2"/><i className="tick t3"/><i className="tick t4"/></div><span className="art-spark s1">✦</span><span className="art-spark s2">✦</span><span className="art-pill"><Check size={13}/>{t("یک قدم جلوتر")}</span></div><h3>{t("کارهای بزرگ، دقیقه‌به‌دقیقه.")}</h3><p>{t("زمان را ثبت کنید، پیشرفت را ببینید")}<br/>{t("و برای کارتان ارزش قائل شوید.")}</p><button className="text-button" onClick={()=>{setPage('reports');choosePreset('month')}}>{t("مرور گزارش این ماه")}{' '}<ArrowUpLeft size={16}/></button></section>}</div>
    {!compact&&<section className="card activities"><div className="section-heading"><div><h2>{t("فعالیت‌های اخیر")}{' '}<span className="count">{number(state.entries.length)}</span></h2><p>{t("ردپای کارهای شما، در یک نگاه")}</p></div><button className="text-button" onClick={()=>setPage('reports')}>{t("مشاهدهٔ گزارش‌ها")}{' '}<ArrowLeft size={16}/></button></div>{recent.length?dates.map(date=><div className="day-group" key={date}><div className="day-heading"><span>{date===today?t("امروز"):dateLabel(date,true)}</span><span className="numeric" dir="ltr">{duration(totals(recent.filter(e=>e.date===date)).ms,true)}</span></div>{entryTable(recent.filter(e=>e.date===date))}</div>):empty()}</section>}</>}
    {page==='reports'&&!compact&&<><section className="card report-filters"><div className="preset-tabs">{[{id:'today',label:t("امروز")},{id:'week',label:t("این هفته")},{id:'month',label:t("این ماه")}].map(p=><button className={preset===p.id?'selected':''} key={p.id} onClick={()=>choosePreset(p.id)}>{p.label}</button>)}<button className={preset==='custom'?'selected':''} onClick={()=>setPreset('custom')}>{t("بازهٔ دلخواه")}</button></div><div className="report-filter-fields"><AssignmentFields state={state} organizationId={reportOrg} projectId={reportProject} filter onChange={(org,project)=>{setReportOrg(org);setReportProject(project)}}/><div className="filter-row"><DatePicker label={t("از تاریخ")} value={range[0]} onChange={v=>{setRange([v,range[1]]);setPreset('custom')}}/><span className="date-divider">—</span><DatePicker label={t("تا تاریخ")} value={range[1]} onChange={v=>{setRange([range[0],v]);setPreset('custom')}}/><label className="search"><Search size={18}/><input aria-label={t("جست‌وجوی فعالیت")} placeholder={t("جست‌وجوی فعالیت…")} value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>{!validRange&&<p className="field-error">{t("تاریخ پایان باید پس از تاریخ شروع یا برابر آن باشد.")}</p>}</section>
    <div className="stats"><Stat icon={<Clock3 size={21}/>} label={t("مجموع زمان کار")} value={duration(report.ms,true)} suffix={t("ساعت : دقیقه : ثانیه")} tone="teal"/><Stat icon={<Wallet size={21}/>} label={t("درآمد این بازه")} value={moneySummary(reportEntries)} suffix="" tone="purple"/><Stat icon={<CheckCircle2 size={21}/>} label={t("فعالیت‌های انجام‌شده")} value={number(report.tasks)} suffix={t("{0} ثبت زمان",number(reportEntries.length))} tone="amber"/></div>
    {reportEntries.length>0&&<div className="report-grid"><section className="card chart-card"><div className="section-heading"><div><h2>{t("تقسیم زمان بین فعالیت‌ها")}</h2><p>{t("سهم هر فعالیت از زمان ثبت‌شده")}</p></div><BarChart3 size={19}/></div><div className="task-bars">{groups.slice(0,5).map((g,i)=><div className="task-bar" key={g.title}><div><span><i style={{background:colors[i]}}/>{g.title}</span><strong className="numeric" dir="ltr">{duration(g.ms,true)}</strong></div><div className="bar-track"><span style={{width:`${g.ms/report.ms*100}%`,background:colors[i]}}/></div></div>)}</div>{groups.length>5&&<p className="muted">{number(groups.length-5)}{t("فعالیت دیگر در جدول جزئیات و PDF")}</p>}</section><section className="card report-note"><span className="note-icon"><FileText size={26}/></span><h3>{t("گزارشی برای ارائه")}</h3><p>{t("جزئیات فعالیت‌ها، زمان کار و مبلغ نهایی.")}</p><button className="outline" disabled={busy} onClick={exportPDF}><ArrowDownToLine size={16}/>{t("خروجی PDF")}</button><small>{t("مبلغ هر ثبت بر اساس نرخ همان فعالیت محاسبه می‌شود.")}</small></section></div>}
    <section className="card activities"><div className="section-heading"><div><h2>{t("جزئیات فعالیت‌ها")}{' '}<span className="count">{number(reportEntries.length)}</span></h2><p>{dateLabel(range[0],true)}{' '}{t("تا")}{' '}{dateLabel(range[1],true)}</p></div><button className="text-button" onClick={()=>openManual()}><Plus size={16}/>{t("ثبت زمان")}</button></div>{reportEntries.length?dates.map(date=><div className="day-group" key={date}><div className="day-heading"><span>{dateLabel(date,true)}</span><span>{moneySummary(reportEntries.filter(e=>e.date===date))}</span></div>{entryTable(reportEntries.filter(e=>e.date===date))}</div>):empty()}{reportEntries.length>0&&<div className="report-total"><strong>{t("جمع کل این بازه")}</strong><span className="numeric" dir="ltr">{duration(report.ms,true)}</span><strong>{moneySummary(reportEntries)}</strong></div>}</section><p className="report-footnote">{t("مبالغ به نزدیک‌ترین تومان گرد می‌شوند. زمان فعالیت در حال اجرا پس از «توقف و ذخیره» وارد گزارش می‌شود.")}</p></>}
    {page==='settings'&&!compact&&<div className="settings-grid"><AppearanceSettings preferences={preferences} busy={preferencesBusy} update={updatePreferences}/><WorkspaceSettings state={state} busy={busy} commit={commit}/><section className="card settings-card"><div className="section-heading"><div><h2>{t("مشخصات و نرخ ساعتی")}</h2><p>{t("ارزش یک ساعت از زمان شما")}</p></div><Wallet size={22}/></div><form onSubmit={saveSettings}><label className="form-label">{t("نام شما")}{' '}<input maxLength={100} placeholder={t("نام و نام خانوادگی")} value={nameInput} onChange={e=>setNameInput(e.target.value)}/></label><label className="form-label">{t("دستمزد ساعتی (تومان / IRT)")}<div className="suffix-input"><input aria-label={t("دستمزد ساعتی")} inputMode="decimal" placeholder={t("مثلاً ۲۵۰۰۰۰")} value={rateInput} onChange={e=>setRateInput(e.target.value)}/><span>{t("تومان")}</span></div></label><div className="settings-hint"><ShieldCheck size={19}/><p>{t("نرخ جدید برای فعالیت‌های بعدی استفاده می‌شود. نرخ فعالیت‌های قبلی و زمان‌سنج جاری حفظ می‌شود؛ برای تغییر آن‌ها، هر ثبت را ویرایش کنید.")}</p></div><button className="primary" type="submit" disabled={busy}><Check size={18}/>{t("ذخیرهٔ تنظیمات")}</button></form></section><section className="card settings-card"><div className="section-heading"><div><h2>{t("اطلاعات شما، در اختیار شما")}</h2><p>{t("پشتیبان‌گیری و بازیابی")}</p></div><ShieldCheck size={22}/></div><p className="settings-description">{t("اطلاعات فقط روی همین دستگاه ذخیره می‌شود. با گرفتن نسخهٔ پشتیبان، فعالیت‌ها و تنظیمات خود را نگه دارید یا به دستگاه دیگری منتقل کنید.")}</p><button className="outline full" onClick={backup}><Download size={18}/>{t("دریافت نسخهٔ پشتیبان")}</button><button className="outline full" disabled={!!a||!window.desktop} onClick={()=>setRestore(true)}><Upload size={18}/>{t("بازیابی از فایل")}</button>{a&&<small className="muted">{t("برای بازیابی، ابتدا زمان‌سنج را متوقف و ذخیره کنید.")}</small>}<div className="storage-path"><span>{t("محل ذخیرهٔ اطلاعات")}</span><code dir="ltr">{dataPath}</code></div><div className="settings-hint"><Pause size={18}/><p>{t("بستن پنجره، برنامه را به سینی سیستم می‌برد و زمان‌سنج ادامه پیدا می‌کند. برای خروج کامل، روی آیکون کنار ساعت راست‌کلیک و «خروج از برنامه» را انتخاب کنید. خواب دستگاه، زمان‌سنج را مکث می‌کند.")}</p></div></section></div>}
    {!compact&&<footer className="app-footer"><span>{t("کارنگار · زمان شما، ارزش شما")}</span><span><span className="status-dot"/> {busy?t("در حال ذخیره…"):t("ذخیره‌شده روی دستگاه")}</span></footer>}</div></main>
    {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{t(toast)}</div>}
    {form&&<Modal title={form.id?t("ویرایش ثبت زمان"):t("ثبت دستی زمان")} close={()=>{if(!busy)setForm(null)}}><form onSubmit={submitEntry}>
      <p className="modal-description">{t('Choose start and end times; work duration is calculated automatically.')}</p>
      <div className="form-label"><span>{t("عنوان فعالیت")}</span><TaskTitleInput state={state} label={t("عنوان ثبت دستی")} placeholder={t("مثلاً طراحی صفحهٔ اصلی")} value={form.title} disabled={busy} onChange={value=>setForm({...form,title:value})} onSelect={entry=>assignForm(entry.organizationId||'',entry.projectId||'',entry.title)}/></div>
      <AssignmentFields state={state} organizationId={form.organizationId} projectId={form.projectId} disabled={busy} onChange={(org,project)=>assignForm(org,project)}/>
      {form.id&&!state.entries.find(e=>e.id===form.id)?.segments?.length&&<p className="time-entry-hint">{t('This older entry has no recorded clock times. Adjust the suggested interval before saving.')}</p>}
      <div className="time-range-fields">
        <div><DatePicker label={t('Start date')} value={form.date} onChange={date=>setForm({...form,date,endDate:form.endDate===form.date?date:form.endDate})}/><label className="form-label">{t('Start time')}<input type="time" step="1" required aria-label={t('Start time')} dir="ltr" value={form.startTime} disabled={busy} onChange={e=>setForm({...form,startTime:e.target.value})}/></label></div>
        <div><DatePicker label={t('End date')} value={form.endDate} onChange={endDate=>setForm({...form,endDate})}/><label className="form-label">{t('End time')}<input type="time" step="1" required aria-label={t('End time')} dir="ltr" value={form.endTime} disabled={busy} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div>
      </div>
      <p className="time-entry-hint">{t('For overnight work, choose the next day as the end date. Paused time is excluded.')}</p>
      <div className="calculated-duration"><span>{t("مدت کار")}</span><strong dir="ltr">{duration(formInterval(form,state.entries.find(e=>e.id===form.id)).ms,true)}</strong></div>
      <label className="form-label">{t('Hourly rate')+' ('+form.currency+')'}<input aria-label={t("نرخ ثبت دستی")} inputMode="decimal" value={form.rate} disabled={busy} onChange={e=>setForm({...form,rate:e.target.value})}/></label>
      <div className="manual-total"><span>{t("مبلغ این فعالیت")}</span><strong>{money(formInterval(form,state.entries.find(e=>e.id===form.id)).ms/3600000*(Number(latin(form.rate))||0),form.currency)}</strong></div>
      {formError&&<p className="field-error" role="alert">{formError}</p>}
      <div className="modal-actions"><button className="primary" type="submit" disabled={busy}><Check size={18}/>{t("ذخیرهٔ زمان")}</button><button className="outline" type="button" disabled={busy} onClick={()=>setForm(null)}>{t("انصراف")}</button></div>
    </form></Modal>}
    {startForm&&<Modal title={t('Edit timer start time')} close={()=>{if(!busy)setStartForm(null)}}><form onSubmit={submitStart}>
      <p className="modal-description">{t('Adjust when this task started. Paused time is excluded.')}</p>
      <DatePicker label={t('Start date')} value={startForm.date} onChange={date=>setStartForm({...startForm,date})}/>
      <label className="form-label">{t('Start time')}<input type="time" step="1" required aria-label={t('Start time')} dir="ltr" value={startForm.time} disabled={busy} onChange={e=>setStartForm({...startForm,time:e.target.value})}/></label>
      {startError&&<p className="field-error" role="alert">{startError}</p>}
      <div className="modal-actions"><button className="primary" type="submit" disabled={busy}><Check size={18}/>{t('Save start time')}</button><button className="outline" type="button" disabled={busy} onClick={()=>setStartForm(null)}>{t("انصراف")}</button></div>
    </form></Modal>}
    {deleting&&<Modal title={t("حذف ثبت زمان")} close={()=>setDeleting(null)}><p className="modal-description">{t("ثبت «")}{deleting.title}{t("» به مدت")}{' '}<b dir="ltr">{duration(deleting.durationMs,true)}</b>{t("حذف شود؟")}</p><div className="modal-actions"><button className="danger-button" disabled={busy} onClick={async()=>{if(await commit({...state,entries:state.entries.filter(e=>e.id!==deleting.id)},t("ثبت زمان حذف شد.")))setDeleting(null)}}><Trash2 size={17}/>{t("حذف ثبت")}</button><button className="outline" onClick={()=>setDeleting(null)}>{t("انصراف")}</button></div></Modal>}
    {restore&&<Modal title={t("بازیابی نسخهٔ پشتیبان")} close={()=>setRestore(false)}><p className="modal-description">{t("فعالیت‌ها و تنظیمات فعلی با اطلاعات فایل انتخابی جایگزین می‌شوند. قبل از بازیابی، نسخهٔ پشتیبان فعلی را دریافت کنید.")}</p><div className="modal-actions"><button className="primary" onClick={importBackup}><Upload size={17}/>{t("انتخاب فایل و بازیابی")}</button><button className="outline" onClick={()=>setRestore(false)}>{t("انصراف")}</button></div></Modal>}
  </div>;
}
function AppearanceSettings({preferences,busy,update}:{preferences:Preferences;busy:boolean;update:(patch:Partial<Pick<Preferences,'theme'|'launchOnStartup'|'language'>>)=>Promise<void>}) {
  return <section className="card settings-card appearance-card">
    <div className="section-heading"><div><h2>{t("ظاهر و راه‌اندازی")}</h2><p>{t("کارنگار، مطابق سلیقهٔ شما")}</p></div><Settings2 size={22}/></div>
    <label className="form-label" htmlFor="language">{t('Language')}</label><select id="language" className="theme-select language-select" value={preferences.language} disabled={busy} onChange={e=>void update({language:e.target.value as Preferences['language']})}><option value="fa">فارسی</option><option value="en">English</option></select>
    <label className="form-label" htmlFor="theme">{t("پوستهٔ برنامه")}</label>
    <select id="theme" className="theme-select" value={preferences.theme} disabled={busy} onChange={e=>void update({theme:e.target.value as Preferences['theme']})}>
      <option value="light">{t("روشن")}</option><option value="dark">{t("تیره")}</option><option value="system">{t("هماهنگ با سیستم")}</option>
    </select>
    <p className="settings-description theme-description">{t("System theme follows your desktop's light and dark settings.")}</p>
    {window.desktop?.platform==='win32'&&<label className="startup-option"><input type="checkbox" checked={preferences.launchOnStartup} disabled={busy} onChange={e=>void update({launchOnStartup:e.target.checked})}/><span><strong>{t("اجرای برنامه هنگام ورود به ویندوز")}</strong><small>{t("پس از روشن کردن دستگاه و ورود به حساب، کارنگار باز می‌شود.")}</small></span></label>}
    <div className="settings-hint"><Minimize2 size={18}/><p>{t("حالت ویجت یا نمای کامل و اندازهٔ پنجره به‌صورت خودکار ذخیره می‌شود و در اجرای بعدی برمی‌گردد.")}</p></div>
  </section>;
}
function Stat({icon,label,value,suffix,tone}:{icon:ReactNode;label:string;value:string;suffix:string;tone:string}) {return <section className="stat card"><div><span className="stat-label">{label}</span><div className="stat-value"><strong className="numeric" dir="ltr">{value}</strong></div><small>{suffix}</small></div><span className={`stat-icon ${tone}`}>{icon}</span></section>}
