import { dateLabel, duration, groupTasks, number, totals, type Entry } from './model';
export const escape = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHTML(entries: Entry[], start: string, end: string, name: string) {
  const total=totals(entries), groups=groupTasks(entries);
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src data:"><style>/* FONT */
  @page{size:A4;margin:17mm 14mm}*{box-sizing:border-box}body{font-family:Arad,sans-serif;color:#1c2c3b;font-size:11px;line-height:1.9}header{border-bottom:3px solid #158575;padding-bottom:18px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:center}h1{font-size:26px;margin:0}h2{font-size:16px;margin-top:26px}.brand{font-size:22px;font-weight:800;color:#158575}.muted{color:#667687}.summary{display:flex;gap:14px}.summary>div{flex:1;padding:16px;background:#eff5f3;border-radius:10px}.summary strong{display:block;font-size:22px}.ltr{direction:ltr;unicode-bidi:isolate;display:inline-block}table{width:100%;border-collapse:collapse;margin:10px 0 24px;table-layout:fixed}thead{display:table-header-group}tr{break-inside:avoid}th{text-align:right;background:#edf2f5;color:#445363;padding:10px 8px;font-weight:600}td{padding:10px 8px;border-bottom:1px solid #e6eaed;overflow-wrap:anywhere}td:first-child{width:32%}footer{border-top:1px solid #d9e2e7;margin-top:26px;padding-top:12px;font-size:10px;color:#667687}.total td{font-weight:700;background:#eff5f3}p{margin:4px 0}</style></head><body>
  <header><div><h1>گزارش زمان و درآمد</h1><p>${dateLabel(start,true)} تا ${dateLabel(end,true)}</p>${name?`<p>نام: ${escape(name)}</p>`:''}</div><div class="brand">کارنگار<p class="muted" style="font-size:11px;font-weight:400">زمان شما، ارزش شما</p></div></header>
  <div class="summary"><div>مجموع زمان<strong class="ltr">${duration(total.ms,true)}</strong></div><div>مبلغ کل<strong>${number(total.amount)}</strong>تومان (IRT)</div><div>تعداد فعالیت‌ها<strong>${number(total.tasks)}</strong>${number(entries.length)} ثبت زمان</div></div>
  <h2>خلاصهٔ فعالیت‌ها</h2><table><thead><tr><th style="width:50%">عنوان فعالیت</th><th>مدت کار</th><th>مبلغ (تومان)</th></tr></thead><tbody>${groups.map(g=>`<tr><td>${escape(g.title)}</td><td><span class="ltr">${duration(g.ms,true)}</span></td><td>${number(g.amount)}</td></tr>`).join('')}</tbody></table>
  <h2>جزئیات ثبت زمان</h2><table><thead><tr><th style="width:30%">عنوان فعالیت</th><th style="width:18%">تاریخ شمسی</th><th style="width:16%">مدت</th><th style="width:17%">نرخ ساعتی</th><th style="width:19%">مبلغ (تومان)</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${escape(e.title)}<p class="muted">${e.source==='manual'?'ثبت دستی':'زمان‌سنج'}</p></td><td>${dateLabel(e.date)}</td><td><span class="ltr">${duration(e.durationMs,true)}</span></td><td>${number(e.rate)}</td><td>${number(e.durationMs/3600000*e.rate)}</td></tr>`).join('')}<tr class="total"><td colspan="2">جمع کل</td><td><span class="ltr">${duration(total.ms,true)}</span></td><td>تومان</td><td>${number(total.amount)}</td></tr></tbody></table>
  <footer><p>مبلغ هر ثبت = مدت کار به ساعت × نرخ ساعتی همان ثبت. مبالغ نمایشی به نزدیک‌ترین تومان گرد شده‌اند؛ جمع کل از مقادیر دقیق محاسبه می‌شود.</p><p>زمان‌ها به صورت ساعت:دقیقه:ثانیه هستند. زمان مکث در محاسبه منظور نمی‌شود. تاریخ‌ها بر اساس تقویم جلالی و روز محلی دستگاه هستند.</p><p>تهیه‌شده با کارنگار · ${dateLabel(new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0')+'-'+String(new Date().getDate()).padStart(2,'0'),true)}</p></footer></body></html>`;
}
